### ISSUE TITLE
PhantomJS does not support Function.bind

### ISSUE THREAD

**Issue by Dormilich** [gruntjs/grunt-contrib-qunit#101]
It should be mentioned somewhere that PhantomJS may not support certain JavaScript features. I found that some of my tests failed due to PhantomJS (1.9.17) not supporting `Function.prototype.bind()` causing a timeout error.

Maybe there could be an error handler that prints such messages to the CLI since all my timeout issues were due to an uncaught JavaScript error.

**Comment by alexdesignworks** [comment]
Use https://github.com/kdimatteo/bind-polyfill

Just include index.js into your html file with unit tests.

**Comment by adamcee** [comment]
Deeplink in above thread to where they say issue is resolved: https://github.com/ariya/phantomjs/issues/10522#issuecomment-72705658

**Comment by jzaefferer** [comment]
Update to the 1.0.0 release of this and you get PhantomJS 2.x.
