### ISSUE TITLE
PhantomJS install failure

### ISSUE THREAD

**Issue by RokaFogtaCsukaFarka** [gruntjs/grunt-contrib-qunit#103]
Hello,

I'm sorry to let you know, that installing this grunt-contrib-qunit package via npm gives me an error.
It is the following:
`>phantom.js@1.19.18 install /localhost/myFolder/`
`>node install.js`
`module.js:338`
`    throw err;`
`     ^`
`Error: Cannot find module '/localhost/myFolder/node_modules/grunt-contrib-`
`qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js'`
 `   at Function.Module._resolveFilename (module.js:336:15)`
`    at Function.Module._load (module.js:278:25)`
`    at Function.Module.runMain (module.js:501:10)`
`    at startup (node.js:129:16)`
`    at node.js:814:3`

Than you for your contribution!

**Comment by Arkni** [comment]
The package [`phantomjs`](https://github.com/Medium/phantomjs) (aka `phantomjs-prebuilt`) is the one responsible for installing and providing us the path of `PhantomJS` binary.
So this issue has nothing to do with this package.

A fresh install should fix the issue. If persist, please report it to https://github.com/Medium/phantomjs.

Closing this for now, feel free to ask if you have followup questions.
