### ISSUE TITLE
Get detailed information for failed assert

### ISSUE THREAD

**Issue by Lipata** [gruntjs/grunt-contrib-qunit#108]
Hello.

Sorry if this is already asked, but I couldn't find it. Thanks in advance for the information.

I'm attaching handlers for all the possible QUnit events: moduleStart, moduleDone, done, error.onError, fail and so on. I'm specifically need a more detailed information for which asserts didn't pass (for example the fail message), not only the number of the failing asserts. I imagined this to be inside the moduleDone event, but the arguments have only information for the count of the failed asserts. Am I missing some configuration and is this possible?

Best regards

**Comment by Arkni** [comment]
Sorry for the late answer. You can use [`QUnit.log(...)`](http://api.qunitjs.com/QUnit.log/), see [/phantomjs/bridge.js#L30-L50](https://github.com/gruntjs/grunt-contrib-qunit/blob/master/phantomjs/bridge.js#L30-L50):
```js
  // These methods connect QUnit to PhantomJS.
  QUnit.log(function(obj) {
    // What is this I don’t even
    if (obj.message === '[object Object], undefined:undefined') { return; }

    // Parse some stuff before sending it.
    var actual, expected, dump;
    if (!obj.result) {
      // In order to maintain backwards compatibility with `QUnit <1.15.0`
      // Older versions of QUnit (`<1.15.0`) use `QUnit.jsDump`, but this poperty was
      // deprecated and moved to `QUnit.dump` and will be removed in `QUnit 2.0`.
      dump = QUnit.dump || QUnit.jsDump;

      // Dumping large objects can be very slow, and the dump isn't used for
      // passing tests, so only dump if the test failed.
      actual = dump.parse(obj.actual);
      expected = dump.parse(obj.expected);
    }
    // Send it.
    sendMessage('qunit.log', obj.result, actual, expected, obj.message, obj.source);
  });
```

Will close this for now, feel free to ask if you have followup question.

**Comment by Lipata** [comment]
Thanks, I will check that.

**Comment by Lipata** [comment]
The following event handler never gets reached:

    grunt.event.on('qunit.log', function (result, actual, expected, message, source) {    });

I'm having the following "grunt-contrib-qunit" version: 1.1.0. In addition I have "grunt-qunit-istanbul", version "0.5.0". Can that be the problem?

Thanks

**Comment by Arkni** [comment]
AFAIK, if you're using `grunt-qunit-istanbul` then you can drop this plugin and you continue using the former.

Also, after exploring the source code of `grunt-qunit-istanbul`, I don't see it prevent the event in question from emitting. I'll test that when the time allows.

**Comment by Lipata** [comment]
Yeah, I have removed the grunt-qunit-istanbul and still I have the same problem. It seems the problem is with my grunt configuration, I guess, so I will continue debugging it. What I wanted to know from you, is that you are sure you don't know something about such a problem with the 'log' event.

Thank you.

**Comment by Arkni** [comment]
> What I wanted to know from you, is that you are sure you don't know something about such a problem with the 'log' event, in some of the grunt-contrib-qunit module versions.

Yes, I'm sure. I've been using this plugin since version `0.4.0` and never encountered that problem.

I don't know what code do you use, but here is a snippet of code using the `qunit.log` event (this is inside `Gruntfile`):
```js
// ...

var assertionsCount = 0;
grunt.event.on("qunit.log", function() {
  assertionsCount++;
});

grunt.registerTask("log", function() {
  // Do something with `assertionsCount`
  console.log(assertionsCount + " assertions passed");
});

// ...

grunt.registerTask("default", [ "qunit", "log" ]);
```
