### ISSUE TITLE
Will grunt-contrib-qunit be updated to support qunit.js 1.20?

### ISSUE THREAD

**Issue by Gruntfuggly** [gruntjs/grunt-contrib-qunit#109]
I would really like to be able to use the nested modules in QUnit 1.20.

Is there a way I can use 1.20 with grunt qunit?

**Comment by jzaefferer** [comment]
This grunt plugin runs your HTML pages through PhantomJS and hooks into QUnit loaded on that page to report results. The version of QUnit loaded on those pages is up to you.
