### ISSUE TITLE
Support request: Firefox browser in CI environment (e.g. Travis)

### ISSUE THREAD

**Issue by MythicAngel** [gruntjs/grunt-contrib-qunit#112]
Hello,

I have some test files which I want to automate via Grunt. Since my code require Firefox browser, I can't make use of this plugin because this plugin runs under phantomjs. Reference repo: https://github.com/MythicAngel/rokeya-keyboard-layout

Is there any to use firefox and this plugin simultaneously in travis-ci? I am aware about other solutions which directly incorporate browser in them, but I want to keep my system very simple therefore want to avoid them.

Thanks,
-R.

**Comment by Arkni** [comment]
> Is there any to use firefox and this plugin simultaneously in travis-ci?

As you said, this plugin only runs under `PhantomJS`, so it's not possible right now to extend it to use something else. But it's not hard to create a similar plugin that runs on [`SlimerJS`](https://github.com/laurentj/slimerjs) which runs on top of `Gecko`, the browser engine of `Mozilla Firefox`. You may need:
* To use the npm package [`slimerjs`](https://github.com/graingert/slimerjs/) that install `SlimerJS` for you.
* To Create a npm wrapper of `SlimerJS` similar to [`grunt-lib-phantomjs`](https://github.com/gruntjs/grunt-lib-phantomjs).

**Comment by timdream** [comment]
@MythicAngel You could check out my setup here (see the recent commits) which do what you wanted.

https://github.com/timdream/jszhuyin

I do agree this is not optimal; Ideally someone should fork `grunt-lib-phantomjs` and make a `grunt-lib-slimerjs` and patch this package to work on either of them (presumably by set them not as dependencies but peerDependencies, and have the user of the new version to install it manually).

**Comment by Arkni** [comment]
Closing this issue as `wontfix` as there are no plans right now to support other [headless] browsers.
