### ISSUE TITLE
Add new flag to reduce logging noise

### ISSUE THREAD

**Issue by illumination517** [gruntjs/grunt-contrib-qunit#116]
Hello, 

I'm currently working on a project with a lot of failing tests in a number of different HTML/JS files (about 50 different modules in total). With each failing test a number of lines of debug are spewed out to the console. This is producing a lot of spam when details of the number of failed tests are available from the 'qunit.done' event. Typically this is about 10+ lines of debug for each failed test, e.g.

`Running "qunit:test-element" (qunit) task
Testing build/tests/element.tests.html .F...
element - HTML wrapped
Message: HTML wrapped correctly
Actual: "<div><h1 id=\"myHeading\"></h1></div>>"
Expected: "<div><h1 id=\"myHeading\"></h1></div>"
at file:///Users/mbailie/workspace/trunk/build/tests/js/libs/thirdparty/qunit-1.18.0.js:1311
  at file:///Users/mbailie/workspace/trunk/build/tests/js/element.tests.js:46
  at file:///Users/mbailie/workspace/trunk/build/tests/js/libs/thirdparty/qunit-1.18.0.js:895
  at file:///Users/mbailie/workspace/trunk/build/tests/js/libs/thirdparty/qunit-1.18.0.js:1024
  at process (file:///Users/mbailie/workspace/trunk/build/tests/js/libs/thirdparty/qunit-1.18.0.js:583)
  at begin (file:///Users/mbailie/workspace/trunk/build/tests/js/libs/thirdparty/qunit-1.18.0.js:628)
  at file:///Users/mbailie/workspace/trunk/build/tests/js/libs/thirdparty/qunit-1.18.0.js:644`

I'd like to propose adding a new flag ('quiet' perhaps?) to try and suppress some of this logging. Any thoughts or opinions?

**Comment by Arkni** [comment]
What do you want to see as output instead ?

**Comment by illumination517** [comment]
I'd like to suppress these error logs entirely and handle the output myself in my own Gruntfile. 

In my particular use case I've integrated my tests with istanbul so I'm printing out a small summary table for each test runner like this; 

  ================ Test Summary ================
  Test Results:    9/10 (31ms)
  Lines:           53.62% (74/138)
  Statements:      53.62% (74/138)
  Functions:       57.69% (15/26)
  Branches:        39.44% (28/71)
  ==============================================

However between each test run I'm getting a lot of the noise mentioned above.

**Comment by Arkni** [comment]
If I'm understanding correctly, you want to disable all errors, so only the warning `Warning: 1/x assertions failed (xxxms) Use --force to continue.` showed up. Am I right ?

Or you want to show something like:
```bash
>> module name  - test name
>> Message: error msg
>> Actual: actual value
>> Expected: expected
```
?

But how can you tell witch test failed and witch one passed ? or this information doesn't interest you ?

**Comment by illumination517** [comment]
> If I'm understanding correctly, you want to disable all errors, so only the warning Warning: 1/x assertions failed (xxxms) Use --force to continue. showed up. Am I right ?

Correct.

> But how can you tell witch test failed and witch one passed ? or this information doesn't interest you ?

In this particular scenario I'm not interested in what tests are passing or failing. I'm just interesting in knowing basic numbers. In the future if I do care about that data I'd either turn the 'suppression' / 'quiet' flag off and use the default handling for error logs or hook into the qunit.log event and do my own customized error logging / handling.

**Comment by Arkni** [comment]
Seems good to me.
I don't know what others think, but I can review a PR if you're willing to implement this feature.

**Comment by vladikoff** [comment]
Sounds good, instead of `quiet` though rename the option to something else, such as `summaryOnly` or something. Also maybe qunit can have a reporter that does this instead?

**Comment by illumination517** [comment]
I agree on the naming of the flag, `quiet` is too generic and implies all output is going to be suppressed. I'm happy to go with `summaryOnly`, I can certainly have a go at implementing it, from reading the code it should only be a couple of lines of code :) I'm not sure I follow your comment about a reporter.

**Comment by vladikoff** [comment]
ok! make sure to add the docs for this option into `docs/`

**Comment by Arkni** [comment]
`silent` maybe ?

> Also maybe qunit can have a reporter that does this instead?

They only have a HTML reporter AFAIK.

**Comment by illumination517** [comment]
I've added a pr;

https://github.com/gruntjs/grunt-contrib-qunit/pull/117

**Comment by illumination517** [comment]
Closing... merged in https://github.com/gruntjs/grunt-contrib-qunit/pull/117.
