### ISSUE TITLE
Add ability to run tests in seeded-random order

### ISSUE THREAD

**Issue by Arkni** [gruntjs/grunt-contrib-qunit#124]
There is a new config in `QUnit` named `seed` added two months ago (jquery/qunit#931). This config tells `QUnit` to run tests in a seeded-random order.

From [`docs`](https://api.qunitjs.com/QUnit.config/):
>**seed** (default: `undefined`)
Type: `String`
This property tells QUnit to run tests in a seeded-random order. The value provided will be used as the seed in a pseudo-random number generator to ensure that results are reproducible. The randomization will also respect the `reorder` option if enabled and re-run failed tests first without randomizing them.
Randomly ordering your tests can help identify non-atomic tests which either depend on a previous test or are leaking state to following tests. This is particularly beneficial in a development CI or post-commit process.

>If `seed` is specified in the page's url parameters, but no value is specified, then QUnit will generate a random value to use as the seed. You can access the value from this property and use it to repeat the same sequence in another run.

-----
I would like to suggest adding a command line option (e.g `--seed`) to pass the seed to `QUnit` as done for filtering by module names (`--modules` recently added in #120).

What do you think?

**Comment by jzaefferer** [comment]
`--seed` CLI option sounds good to me.

**Comment by Arkni** [comment]
PR for this issue: #125
