### ISSUE TITLE
Error while running qunit task with grunt

### ISSUE THREAD

**Issue by gmiano** [gruntjs/grunt-contrib-qunit#126]
Hello,
I am having some problems during test check automatition.
I have writte some tests files which are executed and completed when loaded in a browser.

I am trying to automatize the tests execution within grunt but when I run the task this is printed:
`"C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\gmiano\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt --gruntfile "C:\Users\gmiano\Documents\text-to-speech\TTS API\Gruntfile.js" qunit
Running "qunit:all" (qunit) task
Testing test/qunit.TTS.html 

> > PhantomJS timed out, possibly due to:
> > - QUnit is not loaded correctly.
> > - A missing QUnit start() call.
> > - Or, a misconfiguration of this task.
> >   Testing test/qunit.amd.html 
> >   PhantomJS timed out, possibly due to:
> > - QUnit is not loaded correctly.
> > - A missing QUnit start() call.
> > - Or, a misconfiguration of this task.
> >   Warning: 2/2 assertions failed (0ms) Use --force to continue.

Aborted due to warnings.

Process finished with exit code 6
`

My configuration within the Gruntfile.js is:
`qunit: {
            all: ['test/qunit.*.html'],
        },
`

I am using qunit v1.23.

**Comment by Arkni** [comment]
You can try the solution mentioned in this comment https://github.com/gruntjs/grunt-contrib-qunit/issues/19#issuecomment-90588136

_**Related issues**:_ #19 and #97

**Comment by Arkni** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
