### ISSUE TITLE
Need for encapsulating all code within tests

### ISSUE THREAD

**Issue by brettz9** [gruntjs/grunt-contrib-qunit#128]
I'm new to QUnit itself as well as grunt-contrib-qunit, but I've noticed that I needed to make the following changes to get things working in grunt-contrib-qunit, whereas the changes were not required in the browser (or in grunt-node-qunit for that matter). Without the changes, grunt-contrib-qunit reports only that a single test passes, but doesn't wait to test the 100+ other tests which follow.

```js
QUnit.test('Setting up qunit', function (assert) {
    assert.ok('Queued Unit setup complete');
});
```

to:

```js
QUnit.test('Setting up qunit', function (assert) {
     var done = assert.async();
     assert.ok('Queued Unit setup complete');
     done();
 });
```

and the following in index.html:

```js
function addTest (i) {
    var x = document.createElement('script');
    x.src = testFiles[i];
    x.onload = function () {
        addTestSuite(i + 1);
    };
    document.body.appendChild(x);
}
```

to:

```js
function addTest (i) {
    QUnit.test('Setting up qunit', function (assert) {
        var done = assert.async();
        var x = document.createElement('script');
        x.src = testFiles[i];
        x.onload = function () {
            assert.ok('Loaded test');
            addTestSuite(i + 1);
            done();
        };
        document.body.appendChild(x);
    });
}
```

Is this purely an issue of adding a timeout somewhere? Adding an expanded timeout as a grunt-contrib-qunit option did not seem to work, apparently because that is only for code within tests. Any help would be appreciated.

**Comment by Arkni** [comment]
This should not happen. See examples in [`test`](https://github.com/gruntjs/grunt-contrib-qunit/tree/master/test) folder and the [`Gruntfile`](https://github.com/gruntjs/grunt-contrib-qunit/blob/master/Gruntfile.js) to see how this plugin is used.

Which version of this plugin are you using?
Can you create a reproducible example (a repository here in GitHub that I can check and test)?

**Comment by brettz9** [comment]
If you wouldn't mind taking a look at the `eventtarget-qunit` branch of my fork of IndexedDBShim: https://github.com/brettz9/IndexedDBShim/tree/eventtarget-qunit (and run `npm test`).  (I do not have `saucekey` defined, so it is using the task `qunit`, not `saucelabs-qunit`.)

(For comparison, you can run `grunt dev` and visit `http://localhost:9999/test/index.html` in the browser or, for some similar code running successfully through Node (though not pointed at an HTML file), run `grunt nodequnit` which utilizes `grunt-node-qunit`.)

**Comment by Arkni** [comment]
Thanks!
I'll take a look at it this night.

**Comment by Arkni** [comment]
Before going through the analysis, I would like to quote this from [QUnit docs](https://api.qunitjs.com/QUnit.config/):

> **autostart** (default: `true`)
>
By default `QUnit` runs tests when `load` event is triggered on the `window`. If you're loading tests asynchronously, you can set this property to `false`, then call `QUnit.start()` once everything is loaded.

-----

OK here is the result of my analysis:

##### # Without encapsulating the code within test:

* **Running test in `PhantomJS`**:

First, `PhantomJS` will load the static (`<script>` and `<link>`) `JS` and `CSS` files. This files are loaded in the following order for me:
```md
* queuedUnit.js
* sampleData.js
* startTests.js
* indexeddbshim.min.js
* index.css
* qunit-1.23.1.css
* qunit-1.23.1.js

* and then the bridge file is injected into the page (setting up the handlers)
```
And then the `load` event is triggered on `window` which will result in:
  * `QUnit` starting its setup and trying to run the tests.
  * Calling the method `startTests()` (this will start before `QUnit` can run a test).

`startTests()` will request to load the first test file (a.k.a `DatabaseTests.js`). In the time of loading the file, `QUnt` will already run the test found in `queuedUnit.js` (which the only test available at the time):
```js
QUnit.test('Setting up qunit', function (assert) {
    assert.ok('Queued Unit setup complete');
});
```

After the test is finished, `QUnit` will trigger the `done` event, which will result in this plugin sending kill signal to `PhantomJS`. This will prevent loading the test files, and only one test is executed in total.

* **Running tests in the browser** (`Chromium` and `Firefox`):

Roughly the same steps, except for the last one (_this plugin killing `PhantomJS`_). So the browser will have the time to load all the test files and `QUnit` will execute the tests, as they are added, without a problem.

##### # Solution:

To fix that, you can set `QUnit.config.autostart` to `false` and then call `QUnit.start()` once all test files are loaded.

```diff
 test/index.html | 36 ++++++++++++++++--------------------
 1 file changed, 16 insertions(+), 20 deletions(-)

diff --git a/test/index.html b/test/index.html
index 3b73100..808eb6b 100644
--- a/test/index.html
+++ b/test/index.html
@@ -15,29 +15,25 @@
         <script src="sampleData.js"></script>
         <script src="startTests.js"></script>
         <script>
+            // Prevent `QUnit` from running tests
+            QUnit.config.autostart = false;
+
             function addTest (i) {
-                if (typeof _phantom === 'undefined') { // The sequence below does not work with testId URL params (and adds cruft anyways)
-                    var x = document.createElement('script');
-                    x.src = testFiles[i];
-                    x.onload = function () {
-                        addTestSuite(i + 1);
-                    };
-                    document.body.appendChild(x);
-                    return;
-                }
+                var x = document.createElement('script');
+                x.src = testFiles[i];
+
+                x.onload = function () {
 
-                QUnit.test('Setting up qunit', function (assert) { // Needed to set up as test by grunt-contrib-qunit
-                    var done = assert.async();
-                    var x = document.createElement('script');
-                    x.src = testFiles[i];
-                    x.onload = function () {
-                        assert.ok('Loaded test');
-                        addTestSuite(i + 1);
-                        done();
-                    };
-                    document.body.appendChild(x);
-                });
+                    // All test files are loaded at this stage.
+                    if (testFiles.length === (i + 1)) {
+                        QUnit.start();
+                    }
+
+                    addTestSuite(i + 1);
+                };
+                document.body.appendChild(x);
             }
+
             function runWith () {
                 document.getElementById('qunit-tests').innerHTML = '';
```

I hope this helps!

**Comment by brettz9** [comment]
Wow, this really went above-and-beyond! And yes, I've confirmed it is working...Thank you so much!!

**Comment by Arkni** [comment]
You're welcome!
