### ISSUE TITLE
Is it possible to colorize console logs?

### ISSUE THREAD

**Issue by amenadiel** [gruntjs/grunt-contrib-qunit#136]
My app has log statements reporting which part is being loaded, or which event was triggered. I log them in color in the browser, but the way to color browser's console doesn't work in PhantomJS console output to the terminal.

So I wonder, is there a way to colorize the output? I know you're doing it when my tests turn green :rofl:

**Comment by Arkni** [comment]
You use escape sequences the same way used in [`CasperJS`](https://github.com/casperjs/casperjs/blob/c5186493967d397ef62421b2f876a577370096c8/modules/colorizer.js#L55-L119). All you have to do is detect `PhantomJS`:
```js
var text = "This is a text";

if (window.phantom) {
  // Use escape sequences
  console.log("\033[35;46;1m" + text + "\033[0m");
} else {
  // Color the text the way you do
}
```

**Comment by Arkni** [comment]
Closing this issue for now. Feel free to ask if you have followup questions.
