### ISSUE TITLE
Meaningless error when resources failed to load or there is a script error

### ISSUE THREAD

**Issue by aschekatihin** [gruntjs/grunt-contrib-qunit#145]
I'm back to the project that uses this module and having modified module became burdensome, so i guess it is better to address the issue.
Originally described in PR: #127 

Example:
![image](https://user-images.githubusercontent.com/1819406/28493892-f0328bc2-6f27-11e7-82a9-83b2218238f4.png)

Now if i modify config with large timeout and attach with remote debugger:
![image](https://user-images.githubusercontent.com/1819406/28493899-1a031ba6-6f28-11e7-94c3-e5d2007f7a92.png)

Clearly reported error doesn't provides any help in cases like this and more detailed errors required

**Comment by Krinkle** [comment]
Appears resolved as of https://github.com/gruntjs/grunt-contrib-qunit/pull/182. Please report a new issue if a similar issue is still reproducible on the latest version.
