### ISSUE TITLE
qunit grunt fails with phantomjs

### ISSUE THREAD

**Issue by kanan88** [gruntjs/grunt-contrib-qunit#146]
package.json:
`{
	"name": "666",
	"version": "1.0.0",
	"private": true,
	"devDependencies": {
		"grunt": "~1.0.1",
		"grunt-lib-phantomjs": "~1.1.0",
		"grunt-contrib-clean": "~1.1.0",
		"grunt-contrib-requirejs": "~1.0.0",
		"grunt-text-replace": "~0.4.0",
		"grunt-contrib-qunit": "~2.0.0",
		"grunt-contrib-cssmin": "~2.2.1",
		"grunt-qunit-junit": "~0.3.1"
	}
}`

grunt file qunit part:
		`qunit : {
			all : {
				options : {
					urls : ['../../tests/index.html'],
					timeout : 20000
				}
			}
		},`

During build get error:
`[D] Writing timeout report to _build/test-reports/TEST-index.xml
>> PhantomJS timed out, possibly due to:
>> - QUnit is not loaded correctly.
>> - A missing QUnit start() call.
>> - Or, a misconfiguration of this task.`

Any ideas why it timeouts?

**Comment by DanielRuf** [comment]
Any solutions for this?

**Comment by gh-amistry** [comment]
I'm having the same issue. Was there a fix?
