### ISSUE TITLE
Option 'inject' stopped working in 3.0.0

### ISSUE THREAD

**Issue by Krinkle** [gruntjs/grunt-contrib-qunit#149]
When trying to upgrade [QUnit](https://github.com/qunitjs/qunit)'s own build step from grunt-contrib-qunit 2.x to 3.0.0 I noticed that the build would fail as follows:

```
Running "qunit:qunit" (qunit) task
Warning: The "path" argument must be one of type string, Buffer, or URL. Received type object Use --force to continue.
```

Which comes from:
```js
 var bridgeFile = fs.readFileSync(options.inject, 'utf8'); 
```
at
https://github.com/gruntjs/grunt-contrib-qunit/blob/d18689317c992073076fdbbb85e48641415aeb5c/tasks/qunit.js#L283-L298

Our Gruntfile:

```js
// ..
qunit: {
	options: {
		// ..
		inject: [
			path.resolve( "./build/coverage-bridge.js" ),
			require.resolve( "grunt-contrib-qunit/chrome/bridge" )
		]
	},
	qunit: [
		"test/index.html",
// ..
```

This option is documented in the README as taking `string|Array`, and was recommended by a maintainer at https://github.com/gruntjs/grunt-contrib-qunit/issues/139#issuecomment-279701867.

**Comment by Krinkle** [comment]
This seems to be a regression from https://github.com/gruntjs/grunt-contrib-qunit/pull/147. Prior to that change, the `inject` option was passed down and handled by [grunt-lib-phantomjs:/main.js](https://github.com/gruntjs/grunt-lib-phantomjs/blob/v1.1.0/phantomjs/main.js#L59-L61), which then called [page.injectJs(filepath)](http://phantomjs.org/api/webpage/method/inject-js.html).

**Comment by Arkni** [comment]
Thanks a lot for filling this issue! I'll take a look at it as soon as possible!

I didn't had the time to review #147 and now it's merged (!!!). I will walk through all the changes and see if there are any other regressions.

Thanks!

**Comment by Arkni** [comment]
Hi @Krinkle,

I opened a PR #150 in order to fix this issue and the other one reported in #148. Would love a review from you if you have some time.

Thanks!
