### ISSUE TITLE
Error: PhantomJS timed out, possibly due to a missing QUnit start() call

### ISSUE THREAD

**Issue by jansepar** [gruntjs/grunt-contrib-qunit#15]
I'm getting an issue when setting up a simple qunit test to be run through grunt with phantom:

`PhantomJS timed out, possibly due to a missing QUnit start() call`

I'm kind of stumped, I would love to know what I'm missing!

My grunt file looks like this:

```
    qunit: {
      all: ['tests/*.html']
    },
    connect: {
        server: {
            options: {
                port: 3000,
                base: '.'
            }
        }
    },
```

I'm using these versions:

grunt@0.4.0rc6
grunt-contrib-qunit@0.1.1rc6

And where is what my sample looks like:

```
<html>
<head>
  <meta charset="utf-8">
  <title>Tests</title>
  <link rel="stylesheet" href="/tests/resources/qunit-1.10.0.css">
</head>
<body>
  <div id="qunit"></div>
  <script src="/tests/resources/qunit-1.10.0.js"></script>
  <script>
    console.log("====TEST===")
    test( "hello test", function() {
      ok( 1 == "1", "Passed!" );
    });
  </script>
</body>
</html>
```

I know it's running because I get the console log output. Any help would be much appreciated!

**Comment by fishermand46** [comment]
@jansepar this fixed the problem for me too! Thx for posting!

**Comment by nitinsinghit** [comment]
I am still seeing same error.  This is my grunt file
` qunit: {
            all: {
                options: {
                    urls: [
                        'http://localhost:8000/test/unit/qUnit.html',
                    ]
                }
            }
        },
        connect: {
            server: {
                options: {
                    port: 8000,
                    base: '.'
                }
            }
        },`

**Comment by ajayya** [comment]
```
var triggerSpy = sinon.spy(mediator, 'trigger');
            contentView.uploadModal.$el.on('hidden', function() {
                setTimeout(function() {
                    QUnit.start();
                    ok(triggerSpy.calledWith('alert:success', 'test success'),
                        'Success message should get displayed');
                    ok(triggerSpy.calledWith('alert:warning', 'Some error message'),
                        'Warning message within the pre tags should get displayed');

                    triggerSpy.restore();
                    contentView.close();
                    contentView = null;
                }, 1000);
            });
            contentView.uploadModal.trigger('fileUpload:success', {
                response: '<pre> Some error message   </pre>'
            });
```

 QUnit.start(); not working 
Giving following error- PhantomJS timed out, possibly due to a missing QUnit start() call
