### ISSUE TITLE
Could not load the specified bridge file 

### ISSUE THREAD

**Issue by ossdev07** [gruntjs/grunt-contrib-qunit#157]
Hi ,

I am using grunt-contrib-qunit version 3.0.1 in my package and each time when qunit tests starts to run then I am facing the following issue 

~~~
Running "qunit:files" (qunit) task
Fatal error: Could not load the specified Chrome/QUnit bridge file: false
npm ERR! Test failed.  See above for more details.
~~~

node-version=10.11.0
npm-version=6.5.0
os=Ubuntu 16.04.5
architecture= aarch64 and x86

I will be really thankful if anyone could help me with this, I am open to provide any other information if required to understand the issue.

**Comment by Arkni** [comment]
Hi @ossdev07,

Could you, please, provide your Gruntfile content to see how you are configuring this task?

**Comment by ossdev07** [comment]
Hi @Arkni 

This is my Gruntfile  [Gruntfile.txt](https://github.com/gruntjs/grunt-contrib-qunit/files/2778989/Gruntfile.txt)

Thanks for your help in advance.

**Comment by ossdev07** [comment]
Hi @Arkni 

Thanks for bringing this in my notice, after you have suggested this I have updated my Gruntfile with this:
```
                options: {
                         "--web-security": "no",
                        inject: [
                                   path.resolve("./public/test/coverage-bridge.js"),
                                   require.resolve("grunt-contrib-qunit/chrome/bridge")
                ]
                        page: {
                                viewportSize: { width: 700, height: 500 }
                        }
                }
        },
```
But I am facing the following issue 

```
> grunt

Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected identifier
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
```
Could you please help me with this, really thankful for your time.

**Comment by Arkni** [comment]
Hi @ossdev07,

You forgot to add `,` after the value of property `inject`:
```js
                options: {
                         "--web-security": "no",
                        inject: [
                                   path.resolve("./public/test/coverage-bridge.js"),
                                   require.resolve("grunt-contrib-qunit/chrome/bridge")
                ], // <== You forgot this
                        page: {
                                viewportSize: { width: 700, height: 500 }
                        }
                }
        },
```

**Comment by zachelrath** [comment]
@Arkni I think this issue can be marked as Closed, your answer to @ossdev07 is accurate.

**Comment by Arkni** [comment]
@zachelrath You are right.

Thanks for the reminder :)
