### ISSUE TITLE
Switching to ESM only

### ISSUE THREAD

**Issue by jimmywarting** [gruntjs/grunt-contrib-qunit#181]
To update p-each-series to latest version and keep getting new updates wold require to switch to ESM or using async import()

https://github.com/gruntjs/grunt-contrib-qunit/blob/94d47c7e31306d11b53ac1fd09c1c621941b520d/package.json#L20

Do you have any play on switching to ESM?

**Comment by Krinkle** [comment]
I have no plans to switch internal code to ESM at this time. The package does not export a Node.js API, so this should not affect users.

Thanks for noticing that `p-each-series` is stuck on an old version. I've removed its use in favour of plain JavaScript (for-loop with await).
