### ISSUE TITLE
Test does not run via grunt/phantom, but OK in web browser

### ISSUE THREAD

**Issue by jrburke** [gruntjs/grunt-contrib-qunit#19]
OS 10.8.2, using phantomjs 1.8.1 and grunt v0.3.17:

* git clone --recursive git@github.com:fabien-d/require-qunit-test.git
* grunt qunit (success: "1 assertions passed")
* Edit test/index.html and use the ../vendor/require-2.1.4.js instead of the 2.0.6 script.
* grunt qunit (failure: 0 assertions passed)

This was originally filed as jrburke/requirejs#618. I am filing a ticket here because the require-2.1.4.js version of the test runs fine in QUnit in the browser, just opening test/index.html in a web browser.

While I am open to this being an issue with requirejs, my first thought is it may be due to how the qunit grunt task binds to the running qunit tests and how it detects with QUnit is "done".

One guess at the problem may be that requirejs 2.1.4 waits a bit longer to start the actual qunit test, after whatever signal the grunt qunit driver uses to detect "done".

So, any insight into what I might look at in the grunt qunit code, or pointers is appreciated.

**Comment by markusfalk** [comment]
Found this related to the issue. http://stackoverflow.com/questions/18392463/grunt-not-running-qunit-tests-on-phantom

Is there a solution yet?

**Comment by davidbau** [comment]
I've run into this issue for every requirejs-based grunt-contrib-qunit test I have, in several different projects.  Doesn't affect tests that don't use require.js.

Suspect it is realted this change: db075a2b0a5e0f00390f39538cf6d18ff098673a

**Comment by jzaefferer** [comment]
@davidbau that change is a week old, this issue and most of the comments are much older.

For an example of using QUnit, grunt-contrib-qunit and AMD via requirejs, check out these [two](https://github.com/jquery/qunit/blob/master/test/amd.html) [files](https://github.com/jquery/qunit/blob/master/test/amd.js).

**Comment by Arkni** [comment]
Going to close this out, as @jzaefferer already pointed (https://github.com/gruntjs/grunt-contrib-qunit/issues/19#issuecomment-90588136) to an example of using `QUnit`, `grunt-contrib-qunit` and `requirejs`, which we can consider as a solution.

for a similar solution, see http://stackoverflow.com/a/34928952/3904791
