### ISSUE TITLE
Fail to install "Puppeteer" dependency

### ISSUE THREAD

**Issue by Gabriel-Dias-Oliveira** [gruntjs/grunt-contrib-qunit#205]
Hi, all, I am trying to run a project that has grunt-contrib-qunit as dependency, but I am getting the following:

sudo npm install grunt-contrib-qunit --save-dev
npm ERR! code 1
npm ERR! path /home/gaboliv/Documents/OpenSource/select2/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-09-02T01_27_58_354Z-debug-0.log

344 timing build:link Completed in 2ms
345 info run puppeteer@19.11.1 postinstall node_modules/puppeteer node install.js
346 info run puppeteer@19.11.1 postinstall { code: 1, signal: null }
347 timing reify:rollback:createSparse Completed in 97ms
348 timing reify:rollback:retireShallow Completed in 0ms
349 timing command:install Completed in 18843ms
350 verbose stack Error: command failed
350 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
350 verbose stack     at ChildProcess.emit (node:events:514:28)
350 verbose stack     at maybeClose (node:internal/child_process:1091:16)
350 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
351 verbose pkgid puppeteer@19.11.1
352 verbose cwd /home/gaboliv/Documents/OpenSource/select2
353 verbose Linux 6.2.0-31-generic
354 verbose node v18.17.1
355 verbose npm  v10.0.0
356 error code 1
357 error path /home/gaboliv/Documents/OpenSource/select2/node_modules/puppeteer
358 error command failed
359 error command sh -c node install.js
360 verbose exit 1
361 timing npm Completed in 19005ms

If I remove the grunt-contrib-qunit from the dependency list everything works :(

**Comment by Gabriel-Dias-Oliveira** [comment]
I think this issue is being caused due to compatibility problems between the newest puppeteer version and npm/node versions... Maybe https://github.com/gruntjs/grunt-contrib-qunit/pull/204 will fix this. :D

**Comment by Krinkle** [comment]
grunt-contrib-qunit 8.0 with Puppeteer 21 has been released.
