### ISSUE TITLE
Not able to detect assertions when using requirejs

### ISSUE THREAD

**Issue by kctang** [gruntjs/grunt-contrib-qunit#35]
My qunit tests run fine when accessed from a browser but when executing them through `grunt qunit`, it say:

```
± |master ✗| → grunt qunit
Running "qunit:all" (qunit) task
Testing test/test.htmlOK
Warning: 0/0 assertions ran (15ms) Use --force to continue.

Aborted due to warnings.
```

The test.js file looks something like this:

```
require.config({
    baseUrl: "../app/"
});

require(['my-mod'], function (myMod) {
    test('simple tests', 1, function () {
        // do stuff with myMod
        ok(true, 'works.');
    });
});
```

Once I remove the `require()` functions and move the `test()`block to the top level of the script file, it works:

```
± |master ✗| → grunt qunit
Running "qunit:all" (qunit) task
Testing test/test.html.OK
>> 1 assertions passed (17ms)

Done, without errors.
```

Is there a workaround for this or not a supported feature?

**Comment by hlfcoding** [comment]
I don't believe this works anymore. At least not for my case using v0.7.0

**Comment by StephaneTrebel** [comment]
Same issue here, rolled back to 0.5.1 and it works just fine
