### ISSUE TITLE
bridge.js makes excess processing which results to OutOfMemory

### ISSUE THREAD

**Issue by evil-shrike** [gruntjs/grunt-contrib-qunit#44]
The plugin injects bridge.js script into PhantomJS for tests execution (here is it: https://github.com/gruntjs/grunt-contrib-qunit/blob/master/phantomjs/bridge.js)

There is such code there:
```javascript
  QUnit.log(function(obj) {
    // What is this I don’t even
    if (obj.message === '[object Object], undefined:undefined') { return; }
    // Parse some stuff before sending it.
    var actual = QUnit.jsDump.parse(obj.actual);
    var expected = QUnit.jsDump.parse(obj.expected);
    // Send it.
    sendMessage('qunit.log', obj.result, actual, expected, obj.message, obj.source);
  });
```

I think it's a bad idea to parse (via QUnit.jsDump.parse) all objects being passed into QUnit's methods (like equal).

In my case this code results OutOfMemory due to complexity and recursion in passed objects.

**Comment by Arkni** [comment]
Resolved in #61
