### ISSUE TITLE
Bridge log's obj.message: there's a turtle above the tree

### ISSUE THREAD

**Issue by leobalter** [gruntjs/grunt-contrib-qunit#58]
TL;DR: There's any bug related to [these lines](https://github.com/gruntjs/grunt-contrib-qunit/blob/master/phantomjs/bridge.js#L26-L27) or even any QUnit bug to address and report?

---

There's a [turtle above the tree](https://github.com/gruntjs/grunt-contrib-qunit/blob/master/phantomjs/bridge.js#L26-L27). :)

I don't know what or who put the turtle above the tree since these lines are there since the initial commit of this repo. 

All I know if we see a turtle on a tree, it's because there's a reason to it, otherwise the turtle won't go there alone.

**Comment by Arkni** [comment]
Can we just get rid of that line?
I don't think doing that will affect this plugin and its users.

**Comment by Krinkle** [comment]
Removed in 9.0.0 with https://github.com/gruntjs/grunt-contrib-qunit/commit/23c08c972ebab3675860cab5777bb52283eab945.

Event re-introduced in 9.1.0 with https://github.com/gruntjs/grunt-contrib-qunit/commit/60d05acbb83104580cc78cebc51178c0c6055646, but without this hack. Let's see how it goes. Ref https://github.com/gruntjs/grunt-contrib-qunit/issues/207.
