### ISSUE TITLE
grunt-contrib-qunit is 10x to 20x slower than running the tests in my browser

### ISSUE THREAD

**Issue by tieTYT** [gruntjs/grunt-contrib-qunit#65]
My package.json says: "grunt-contrib-qunit": "^0.4.0".  This probably has to do with PhantomJS, but maybe it has to do with how this plugin is using PhantomJS so I'll post this here.  

Running all my tests in Firefox takes ~1 second and in Chrome ~.5 seconds, but the grunt-contrib-qunit plugin takes ~11 seconds.  

Here's a link to the debug output of PhantomJS when my test runs: https://gist.github.com/tieTYT/7faa0b6e8669f4ea4ac1

I'm sure some of this time has to do with how PhantomJS must start up every time and Firefox / Chrome are already open, but I can see with my eyes that the tests themselves are taking a lot of time, so it's not just the start up time.

Is there anything that can be done about this?  Is there anything I can do?

**Comment by Arkni** [comment]
@tieTYT are you still encountering the same issue using the latest release (`v1.0.x`) ?

**Comment by Arkni** [comment]
Closing due to the lack of feedback!
Feel free to ask if you have followup question.
