### ISSUE TITLE
Allow lazy evaluation of the urls

### ISSUE THREAD

**Issue by martin-g** [gruntjs/grunt-contrib-qunit#76]
I need to use Connect's useAvailablePort (https://github.com/gruntjs/grunt-contrib-connect#useavailableport) because sometimes the CI server already runs a build for another branch and grunt-contrib-connect fails to bind the port.

It would be nice if `urls` array supports values with type `function` to lazy evaluate them.
This way I could use https://github.com/gruntjs/grunt-contrib-connect#oncreateserver to get the port value and use it in the url.

At the moment my workaround is to use different ports for the different branches.

**Comment by Arkni** [comment]
PR is welcome :) if you still interested in this feature.
