### ISSUE TITLE
programatically inject html snippets into qunit-fixture

### ISSUE THREAD

**Issue by markusfalk** [gruntjs/grunt-contrib-qunit#78]
do you think it would be a good idea to have a hook before and after each test to use another grunt task to inject html into the qunit-fixture?

```javascript
qunit: {  
  options: {
    setup: ['task-inserting-html-into-fixture'], // grunt-replace for example
    teardown: ['task-removing-html-from-fixture'] // grunt-contrib-clean for example
  },
  all: {
      files: 'test/test-suite.html'
  }
}
```

or as I am already wishing for something maybe the qunit task could do that itself:

```javascript
qunit: {  
  all: {
    html: 'html/**/*.html', // globbing pattern to file that is inserted into the qunit-fixture before each test
    files: 'test/test-suite.html'
  }
}
```

This way there still is no connection to the test itself. That means after inserting the html the task won't know what test needs this snippet. Maybe this could be done with naming convention?

```javascript
qunit: {  
  all: {
    files: 'test/test-suite.html' // test.js is linked in that file and test.html gets injected?
  }
}
```

Then I would have to create endless many test-suites that all link to another tests.js file. Still better than inserting the html myself and having to maintain 2 copies of it (actual template file and qunit-fixture contents) :-/

Or maybe there is a better way to insert pieces of html into the fixture programmatically?

**Comment by Arkni** [comment]
I see that you already fixed your problem in above linked issue.

Closing for now, feel free to ask if you have followup question.
