### ISSUE TITLE
QUnit callback methods & arguments don't match the QUnit cookbook

### ISSUE THREAD

**Issue by kmudrick** [gruntjs/grunt-contrib-qunit#79]
What's the rational for supplying the grunt qunit event callbacks with multiple arguments instead of a single argument with the details?

Example: QUnit.testStart (http://api.qunitjs.com/QUnit.testStart/) invokes the callback with an argument containing both the name and the module, but the grunt qunit.testStart event supplies just the name, as a single argument

**Comment by Arkni** [comment]
> Example: QUnit.testStart (http://api.qunitjs.com/QUnit.testStart/) invokes the callback with an argument containing both the name and the module, but the grunt qunit.testStart event supplies just the name, as a single argument

You're right, but we use [`QUnit.moduleStart()`](http://api.qunitjs.com/QUnit.moduleStart/) which provide us with the name of the current running `module`.

> But I can't see any place where this is logged if a test suite fails.

It's concatenated to the name of the test (https://github.com/gruntjs/grunt-contrib-qunit/blob/master/tasks/qunit.js#L81)

Closing this for now, feel free to ask if you have followup questions.
