### ISSUE TITLE
Cannot test when QUnit is asynchronously loaded through RequireJS

### ISSUE THREAD

**Issue by christopherliu** [gruntjs/grunt-contrib-qunit#80]
This may be related to https://github.com/gruntjs/grunt-contrib-qunit/issues/19 but it looks different.

I've been using the [QUnit RequireJS demo](https://github.com/jonnyreeves/qunit-require) here, which successfully runs both in the browser and through this grunt task. However, when I [modify that version](https://github.com/christopherliu/qunit-require/) to load asynchronously, it works in the browser, but not in Grunt.

I ran Grunt --debug and noticed the following error message halfway through:
```
[D] ["phantomjs","inject","C:\\Users\\C\\Desktop\\qunit-require-
master\\node_modules\\grunt-contrib-qunit\\phantomjs\\bridge.js"]
[D] ["phantomjs","error.onError","ReferenceError: Can't find variable: QUnit",[{
"file":"C:\\Users\\C\\Desktop\\qunit-require-master\\node_module
s\\grunt-contrib-qunit\\phantomjs\\bridge.js","line":14,"function":""},{"file":"
C:\\Users\\C\\Desktop\\qunit-require-master\\node_modules\\grunt
-contrib-qunit\\phantomjs\\bridge.js","line":58,"function":""}]]
```

If I attach logs to each function, it's clear that bridge.js is running before QUnit is fully injected.

**Comment by jzaefferer** [comment]
See previous comment. Will close since issue seems to be resolved or invalid.

**Comment by christopherliu** [comment]
Update: I think the problem here was that bridge.js was injected into Phantom as a synchronous script, so it only worked when QUnit was loaded synchronously.

It looks like async functionality was added by [this commit](https://github.com/gruntjs/grunt-contrib-qunit/pull/94), which I'll have to try sometime.
