### ISSUE TITLE
Multiple `console` event handlers added

### ISSUE THREAD

**Issue by marsmining** [gruntjs/grunt-contrib-qunit#84]
Everytime the qunit task is triggered by a file change, via the watch task, calls to `console.log` are printed N times where N is the number of times the watch task has triggered the qunit task.

https://github.com/gruntjs/grunt-contrib-qunit/blob/v0.5.2/tasks/qunit.js#L185

**Comment by Arkni** [comment]
There is an option to suppress that behavior (https://github.com/gruntjs/grunt-contrib-qunit#console)

Closing for now, feel free to ask if you have followup question.
