### ISSUE TITLE
Grunt exit code of zero even when tests fail

### ISSUE THREAD

**Issue by craig0990** [gruntjs/grunt-contrib-qunit#86]
Grunt always returns from a set of QUnit tasks with an exit code of 0, even if some assertions fail.

Personally, I find this strange - I want a non-zero exit code if tests fail, and a zero code if they all pass.

Implementing this is easy (pull request #85 ), by passing the results information back through the `done()` callback in the task, but has the side-effect of breaking the tests for the module itself.

I can't (currently) think of a way to test the `noglobals` support without a purposely failing test, so I'm adding this issue to ask what the developers think.

**Comment by scottgonzalez** [comment]
Fixed in 8012c24ec96e0510fa36e07e445bb30ef62750cd.
