### ISSUE TITLE
Documentation includes features from the future

### ISSUE THREAD

**Issue by starwed** [gruntjs/grunt-contrib-qunit#87]
The README pretends to be documentation for the currently released version (0.5.2), but it includes features which will be in the next release (such as the `noGlobals` flag).

**Comment by jzaefferer** [comment]
Versioned docs:

* https://www.npmjs.com/package/grunt-contrib-qunit (latest release)
* https://github.com/gruntjs/grunt-contrib-qunit/tree/v0.5.2#grunt-contrib-qunit-v052-- (0.5.2 tag)

**Comment by starwed** [comment]
The basic problem is that if you search for something like "grunt-contrib featureX", where featureX isn't implemented in the release verison, it'll bring you to the docs on this github repo.  So what I'm really asking for is for the docs here to have the correct version, or to note explicitly, at the top, that they're for the development branch.

**Comment by jzaefferer** [comment]
Sure, but this applies to most repositories on GitHub, which default to showing the master branch. Adding a line like "this is master" would be easy to miss and would make releases more complicated.

The bigger problem is probably that features are added, but not released. With npm modules its so trivial to publish new releases that it should happen whenever a feature lands in master.

**Comment by jzaefferer** [comment]
Its pretty bad that the readme actually includes the version number of the previous release, along with docs for unreleased features. That's actively misleading and probably contributed to the confusion. That seems to be part of the build-contrib task, so I'm not sure what to do there.

For what its worth, I've just published 0.6.0 to npm, so for now the readme on GitHub and latest release are correct.
