### ISSUE TITLE
My test work in Chrome, but PhantomJS times out  (not using dynamic modules)

### ISSUE THREAD

**Issue by boris-marinov** [gruntjs/grunt-contrib-qunit#89]
When my test suite grew too large I started having the above problem:

PhantomJS timed out, possibly due to a missing QUnit start() call.

So far I tried:
- Updating the packages
- Running tests in a web server.

I am not using a dynamic file loader. 

The test works if I remove some of my dependencies, so I assume it is a race condition.

**Comment by boris-marinov** [comment]
Caused by a syntax error in my JS (trying to call Object.keys with a string). How can I check if PhantomJS returned any errors while executing the script?

**Comment by maboiteaspam** [comment]
If i remember correctly, it displays in output. Have you tried to increase log level ?

**Comment by boris-marinov** [comment]
Not really (I am not familliar with PhantomJS's settings)

**Comment by maboiteaspam** [comment]
check your package version first.

check console option in your task options.
https://github.com/gruntjs/grunt-contrib-qunit#console

Try with --debug.

you may also reduce the timeout. That should trigger the failure sooner. timeout should fail the test.

Finally you can listen to error events in grunt
https://github.com/gruntjs/grunt-contrib-qunit#events-and-reporting

**Comment by boris-marinov** [comment]
Thanks, I fixed my issue. Maybe this should spit the errors out of the box.
