### ISSUE TITLE
testing with AMD is not working

### ISSUE THREAD

**Issue by hackerwins** [gruntjs/grunt-contrib-qunit#97]
Hi guys.
First of all, thanks for nice module. I'm a big fan.

I found my test(http://goo.gl/Ee3WDB) is not working anymore after `grunt-contrib-qunit` support amd.
I included qunit globally Because old version wasn't support amd.
So I include qunit with amd and update libs(qunit and amd). But It's still not working.

I tried to debug this but I can't figure it out after all.
I just found `bridge.js`'s `factory` is never called with amd.

```javascript
 (function (factory) {
   if (typeof define === 'function' && define.amd) {
     console.log('this is called');
     require(['qunit'], factory);
   } else {
     factory(QUnit);
   }
 }(function(QUnit) {
   'use strict';
   console.log('this code never called');

   // Don't re-order tests.
   QUnit.config.reorder = false;
   // Run tests serially, not in parallel.
   QUnit.config.autorun = false;
```

Could you give me advice or added some test code with requirejs?

**Comment by jzaefferer** [comment]
There's not enough information here to help. You'd have to put together a reduced test page.

**Comment by markusfalk** [comment]
I have a similar problem. My setup was working with grunt-contrib-qunit@0.5.2 but returns a phantomJs timeout with grunt-contrib-qunit@0.7.0.

I have described the problem here in detail: http://stackoverflow.com/questions/29435486/how-to-setup-grunt-task-for-requirejs-and-qunit

**Comment by jzaefferer** [comment]
I actually forked and cloned your repo. After taking forever to install all the dependencies, it failed running the compass task. I'm not interested in debugging that. Could you provide a (massively) reduced test case that focuses on the grunt-contrib-qunit failure? I could check that out.

Meanwhile, try requiring QUnit via AMD and remove the lines that change `QUnit.config`. Or check [this example](https://github.com/jquery/qunit/blob/master/test/amd.html).

**Comment by markusfalk** [comment]
Thanks for your efforts. I have reduced the setup to focus on the qunit failure. Also I have created a branch (20150411_falk_require-qunit-as-amd) that uses the setup of your amd example. Same results.

**Comment by jzaefferer** [comment]
I've refactored your setup a bit, but it still doesn't fix the problem: https://github.com/markusfalk/test-travis/pull/1 - maybe you have more lack with that as a starting point.

**Comment by markusfalk** [comment]
I reworked my branch to something similar to what you have done in your example but still no luck. https://travis-ci.org/markusfalk/test-travis/builds/58909816

@HackerWins have you made any progress on the issue?

**Comment by markusfalk** [comment]
I found a working (https://travis-ci.org/markusfalk/test-travis) setup: https://github.com/markusfalk/test-travis/tree/20150411_falk_require-qunit-as-amd/qunit

**Comment by jzaefferer** [comment]
So what did you change to make it work with Phantom?

**Comment by Arkni** [comment]
@markusfalk already solved his issue, see http://stackoverflow.com/a/29890894/3904791
@hackerwins do you still encountering the same issue ? maybe you can try @markusfalk's solution.

Closing this for now, feel free to ask if you have followup questions.
