### ISSUE TITLE
Only if assertions fail: PhantomJS timed out, possibly due to a missing QUnit start() call

### ISSUE THREAD

**Issue by sdd64** [gruntjs/grunt-contrib-qunit#98]
Error above only comes when at least one out of n specs is failing.

I want to use your code to test a SAPUI5 application. Here is my Gruntfile.js
     module.exports = function(grunt) {
       grunt.loadNpmTasks("grunt-contrib-qunit");

       grunt.initConfig({
         qunit: {
          all: ["OpaMatchers.html"]
        }
      });
    };

When all my (currently two) specs pass, I get the expected Output

      .OK
      >> 2 assertions passed (11606ms)

However, If only one of them fails I get:

      >> PhantomJS timed out, possibly due to a missing QUnit start()
     Warning: 1/1 assertions failed (0ms) Use --force to continue.

**Comment by jzaefferer** [comment]
Please provide a reduced testcase that let's other reproduce the issue. As is there's not enough information here to help you.

**Comment by sdd64** [comment]
I replicated my test setup in another application. Using pure QUnit specs is fine, there may fail n out of m specs and PhantomJS stays alive. 

Seems to me, the issue comes from OPA5. I guess this issue can be closed
